import sharp from 'sharp';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PHOTOS, WARM_MATRIX, WARM_MODULATE, WIDTHS } from './photos.config.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'static/photos');
const manifestFile = path.join(root, 'src/lib/data/photos.generated.ts');

await mkdir(outDir, { recursive: true });

/**
 * Crops a window around a normalised focal point. `zoom` > 1 tightens the
 * frame; `aspect` is width/height of the output window.
 */
function focusWindow({ width, height }, { x = 0.5, y = 0.5, zoom = 1, aspect }) {
	const targetAspect = aspect ?? width / height;
	let cropH = height / zoom;
	let cropW = cropH * targetAspect;

	if (cropW > width) {
		cropW = width;
		cropH = cropW / targetAspect;
	}
	if (cropH > height) {
		cropH = height;
		cropW = cropH * targetAspect;
	}

	const left = Math.max(0, Math.min(width * x - cropW / 2, width - cropW));
	const top = Math.max(0, Math.min(height * y - cropH / 2, height - cropH));

	return {
		left: Math.round(left),
		top: Math.round(top),
		width: Math.round(cropW),
		height: Math.round(cropH)
	};
}

function resolveSource({ file, dir }) {
	return path.isAbsolute(file) ? file : path.join(dir, file);
}

async function pipeline(photo) {
	const source = resolveSource(photo);
	const meta = await sharp(source).autoOrient().metadata();
	let image = sharp(source).autoOrient();
	if (photo.focus) image = image.extract(focusWindow(meta, photo.focus));
	const cropped = photo.focus
		? focusWindow(meta, photo.focus)
		: { width: meta.width, height: meta.height };
	return {
		width: cropped.width,
		image: image.recomb(WARM_MATRIX).modulate(WARM_MODULATE)
	};
}

/** Widths above the source resolution are dropped so nothing is upscaled. */
async function render(photo) {
	const { width: srcWidth } = await pipeline(photo);
	const widths = WIDTHS.filter((w) => w <= srcWidth);
	if (widths.length === 0) widths.push(srcWidth);

	const renders = await Promise.all(
		widths.map(async (w) => {
			const { image: frame } = await pipeline(photo);
			return frame
				.resize({ width: w })
				.webp({ quality: 88, effort: 5 })
				.toFile(path.join(outDir, `${photo.slug}-${w}.webp`));
		})
	);

	const largest = renders.at(-1);
	return { slug: photo.slug, widths, aspect: +(largest.width / largest.height).toFixed(4) };
}

const entries = [];
for (const photo of PHOTOS) {
	entries.push(await render(photo));
	console.log(`graded ${photo.slug}`);
}

const keep = new Set(entries.flatMap((e) => e.widths.map((w) => `${e.slug}-${w}.webp`)));
for (const name of await readdir(outDir)) {
	if (!name.endsWith('.webp') || keep.has(name)) continue;
	await rm(path.join(outDir, name));
	console.log(`removed ${name}`);
}

const body = entries
	.map((e) => `\t'${e.slug}': { widths: [${e.widths}], aspect: ${e.aspect} }`)
	.join(',\n');

await writeFile(
	manifestFile,
	`// Generated by scripts/photos.mjs — run \`npm run photos\` to refresh.\n` +
		`export const photoFiles = {\n${body}\n} as const;\n\n` +
		`export type PhotoSlug = keyof typeof photoFiles;\n`
);

console.log(`\n${entries.length} photos -> static/photos, manifest -> ${manifestFile}`);
