import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PHOTOS, SOURCE_DIR, WARM_MATRIX, WARM_MODULATE, WIDTHS } from './photos.config.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'static/photos');
const manifestFile = path.join(root, 'src/lib/data/photos.generated.ts');

await mkdir(outDir, { recursive: true });

/**
 * Crops a window around a normalised focal point. `zoom` > 1 tightens the
 * frame; `aspect` is width/height of the output window.
 */
function focusWindow({ width, height }, { x = 0.5, y = 0.5, zoom = 1, aspect }) {
	const targetAspect = aspect ?? width / height;
	let cropH = height / zoom;
	let cropW = cropH * targetAspect;

	if (cropW > width) {
		cropW = width;
		cropH = cropW / targetAspect;
	}
	if (cropH > height) {
		cropH = height;
		cropW = cropH * targetAspect;
	}

	const left = Math.max(0, Math.min(width * x - cropW / 2, width - cropW));
	const top = Math.max(0, Math.min(height * y - cropH / 2, height - cropH));

	return {
		left: Math.round(left),
		top: Math.round(top),
		width: Math.round(cropW),
		height: Math.round(cropH)
	};
}

async function pipeline(file, focus) {
	const source = path.join(SOURCE_DIR, file);
	const meta = await sharp(source).autoOrient().metadata();
	let image = sharp(source).autoOrient();
	if (focus) image = image.extract(focusWindow(meta, focus));
	const cropped = focus ? focusWindow(meta, focus) : { width: meta.width, height: meta.height };
	return {
		width: cropped.width,
		image: image.recomb(WARM_MATRIX).modulate(WARM_MODULATE)
	};
}

/** Widths above the source resolution are dropped so nothing is upscaled. */
async function render({ slug, file, focus }) {
	const { width: srcWidth } = await pipeline(file, focus);
	const widths = WIDTHS.filter((w) => w <= srcWidth);
	if (widths.length === 0) widths.push(srcWidth);

	const renders = await Promise.all(
		widths.map(async (w) => {
			const { image: frame } = await pipeline(file, focus);
			return frame
				.resize({ width: w })
				.webp({ quality: 88, effort: 5 })
				.toFile(path.join(outDir, `${slug}-${w}.webp`));
		})
	);

	const largest = renders.at(-1);
	return { slug, widths, aspect: +(largest.width / largest.height).toFixed(4) };
}

const entries = [];
for (const photo of PHOTOS) {
	entries.push(await render(photo));
	console.log(`graded ${photo.slug}`);
}

const body = entries
	.map((e) => `\t'${e.slug}': { widths: [${e.widths}], aspect: ${e.aspect} }`)
	.join(',\n');

await writeFile(
	manifestFile,
	`// Generated by scripts/photos.mjs — run \`npm run photos\` to refresh.\n` +
		`export const photoFiles = {\n${body}\n} as const;\n\n` +
		`export type PhotoSlug = keyof typeof photoFiles;\n`
);

console.log(`\n${entries.length} photos -> static/photos, manifest -> ${manifestFile}`);
