// Generated by scripts/photos.mjs — run `npm run photos` to refresh.
export const photoFiles = {
	'hero-wide': { widths: [640,1024,1600,2400], aspect: 1.5 },
	'hero-tall': { widths: [640,1024,1600,2400], aspect: 0.6667 },
	'studio-arches': { widths: [640,1024,1600,2400], aspect: 1.5831 },
	'group-profile': { widths: [640,1024,1600,2400], aspect: 1.5 },
	'group-stairs': { widths: [640,1024,1600,2400], aspect: 0.667 },
	'group-embrace': { widths: [640,1024,1600,2400], aspect: 1.5 },
	'group-reach': { widths: [640,1024,1600,2400], aspect: 1.5 },
	'solo-arch': { widths: [640,1024,1600,2400], aspect: 1.5 },
	'solo-motion': { widths: [640,1024,1600,2400], aspect: 0.6667 },
	'founder': { widths: [640,1024,1600], aspect: 0.8 },
	'hands': { widths: [640,1024,1600,2400], aspect: 1.3994 },
	'blooms': { widths: [640,1024,1600,2400], aspect: 1.4484 },
	'bloom-soft': { widths: [640,1024,1600,2400], aspect: 0.6148 },
	'veil': { widths: [640,1024,1600,2400], aspect: 0.7143 }
} as const;

export type PhotoSlug = keyof typeof photoFiles;
