server {
    listen 80;
    server_name  empathy-studio.lt www.empathy-studio.lt;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


server {
    listen       443 ssl;
    server_name  empathy-studio.lt www.empathy-studio.lt;

    ssl_certificate     /etc/letsencrypt/live/empathy-studio.lt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/empathy-studio.lt/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /robots.txt {
       add_header Content-Type text/plain;
       try_files $uri =404;
    }

    location / {
        try_files $uri.html $uri $uri/ =404;
    }

    #error_page  404              /404.html;
}